services:
  nginx:
    build:
      context: ./requirements/nginx/
    container_name: nginx_c
    ports:
      - '443:443'
    networks:
        - inception
      
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb_c
    expose:
      - '3306'
    networks:
        - inception
    env_file:
        - .env

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress_c
    expose:
      - '9000'
    networks:
        - inception
    env_file:
        - .env

networks:
  inception:
    name: inception

volumes:
  mariadb:
#     name: mariadb_data
#     driver_opts:
#       type: none
#       device: $HOME/data/mariadb
#       o: bind

  wordpress:
#     name: wordpress_data
#     driver_opts:
#       type: none
#       device: $HOME/data/wordpress
#       o: bind
