services:
  nginx:
    build:
      context: ./requirements/nginx/
    # image: nginx_i
    container_name: nginx_c
    ports:
      - '443:443'
    networks:
        - inception
      
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb_c
    expose:
      - '3306'
    networks:
        - inception

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress_c
    expose:
      - '9000'
    networks:
        - inception

networks:
  inception:
    name: inception
