services:
  nginx:
    build:
      context: ./requirements/nginx/
    container_name: nginx
    env_file: .env
    restart: on-failure
    ports:
      - '443:443'
    depends_on:
      - wordpress
    networks:
        - inception
    volumes:
      - wordpress:/var/www/html
      
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file: .env
    restart: on-failure
    expose:
      - '3306'
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u root -p${SQL_ROOT_PASSWORD}
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    env_file: .env
    restart: on-failure
    expose:
      - '9000'
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html

networks:
  inception:
    name: inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/heda-sil/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/heda-sil/data/wordpress
