services:
  nginx:
    build:
      context: ./requirements/nginx/
    image: nginx_i
    container_name: nginx_c
    ports:
      - '443:443'
      
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb_c
    expose:
      - '3306'

# TODO: Add wordpress
# TODO: Add networks
